### ISSUE TITLE
save accounts to txt file in custom format

### ISSUE THREAD

**Issue by aysx** [sag-enhanced/sage-issues#24]
### Describe the feature

Add a function for saving accounts in txt file with custom format such as: "login:" {username} "pass:" {password} e-mail: {email} 

### Use case

no needs to use discord webhooks, 
easier to save somewhere on pc,
easier to manage those accounts compare on discord and prolly more

**Comment by Le0Developer** [comment]
Export as raw JSON and then process that?
Like adding a custom function feature to exporting would do the exact same thing.

**Comment by Le0Developer** [comment]
This is now implemented.
<img width="388" alt="image" src="https://github.com/sag-enhanced/sage-issues/assets/40232557/ede0df60-7e89-432a-9232-12f7bb7a4f11">

Example script for your format:
```js
return (ctx) => {
  return ctx.accounts.map(x => [
    `login: ${x.user.username}`,
    `pass: ${x.user.password}`,
    `email: ${(x.vault || x.email).address}`,
  ].join("\n")).join("\n\n");
}
```
