### ISSUE TITLE
steam family view activation 

### ISSUE THREAD

**Issue by xnoit** [sag-enhanced/sage-issues#39]
### Describe the feature

the ability to choose whether to enable family view when creating an account (similar to choosing steam guard enabled/disabled). can be added in customization section in settings, where user can define pin, turn on/off family view, etc.
probably easier to implement than steam guard disabler (no need to login into desktop client)

### Use case

family view settings automation

**Comment by Le0Developer** [comment]
Why would you want this?

For me: https://store.steampowered.com/parental/set/

**Comment by xnoit** [comment]
I mostly use family view to be sure that no one can change preferences,
settings, email, profile settings etc. It is great way to secure accounts.
And a lot of services that I use generated accounts for, they require
family view as additional security.
Or maybe accounts for rent, but i am not in this shi
Main problem with family view is that you need to login into every account,
then do a lot of clicking, wait for email, load sage mail, so all of that
probably loads the server. And to turn on family view on thousand of
accounts, I thought it is easier and more resource effective to implement
this feature into sage. If there will be something like that, I think some
people will use it too


Вс, 7 июля 2024 г. в 15:40, Leo Developer ***@***.***>:

**Comment by Le0Developer** [comment]
Would it be the same PIN across all accounts? also what would the recovery email be?

**Comment by xnoit** [comment]
I use the same pin for all my accounts and the same email that account
registered with. With sage accounts I don’t really know for sure, but can
recovery email be used as standard permanent email?

Вт, 9 июля 2024 г. в 14:03, Leo Developer ***@***.***>:

**Comment by xnoit** [comment]
I thought about some parameter that you can change in settings and all new
accounts are generated with this pin, if family view option is enabled.

Вт, 9 июля 2024 г. в 14:03, Leo Developer ***@***.***>:

**Comment by Le0Developer** [comment]
Email verification is very spotty
