### ISSUE TITLE
Shrinking files breaks set/get

### ISSUE THREAD

**Issue by BaldCult** [sag-enhanced/sage-issues#40]
### Prerequisites

- [X] I asked in the [Discord server](https://sage.party/discord) and have been directed here.

### Describe the bug

Causes the app to be a blank screen when opening it and to fix it ratelimits.dat needs to be deleted.

### To Reproduce

Don't know!

**Comment by Le0Developer** [comment]
Can't repro, might be windows exclusive.

**Comment by Le0Developer** [comment]
Can't repro on windows either. This is frustrating since I know the issue exists, but I just can't repro it

**Comment by Le0Developer** [comment]
Released b10 with a potential fix.

**Comment by Le0Developer** [comment]
Not fixed. (HOW)
