### ISSUE TITLE
Autojoin Groups

### ISSUE THREAD

**Issue by LumixCode** [sag-enhanced/sage-issues#41]
### Describe the feature

Set groups, which new accounts should automatically join.

### Use case

In my case I want to make a huge group with all my available accounts.
This also allows me to see all accounts without having to open sage.

**Comment by Le0Developer** [comment]
![image](https://github.com/sag-enhanced/sage-issues/assets/40232557/29578554-ad5b-4b2e-af4e-cad30395e189)
