### ISSUE TITLE
Custom settings import/export with JSON

### ISSUE THREAD

**Issue by callmejaf** [sag-enhanced/sage-issues#42]
### Describe the feature

In the settings menu, it would be beneficial to have an option to import and export the configuration settings in JSON format. This feature would act as presets for the generation of different types of accounts.

### Use case

This feature would allow users to configure settings from outside the Sage application, using other programming languages or simply to save settings presets. It would provide flexibility for integrating Sage with other tools and automating configurations.

### Additional context

For example, in my use case: If integrating with a Discord bot using Discord.py, the user could select a custom username, region, and password directly on Discord, as well as set privacy options. Python could handle the backend, verifying the username's availability and configuring the settings in JSON format for account name, password, and privacy settings. Additionally, it could configure the proxy settings in JSON format based on the selected region. Then, the Python script (or any other program) could import these settings into Sage using a tool like winautomate to automate the process - letting sage do the rest of the account generation

**Comment by Le0Developer** [comment]
Already possible, see Discord discussion for details: https://discord.com/channels/1008806317474971740/1008808482394361866/1246476099819405333
