### ISSUE TITLE
Acccount manager

### ISSUE THREAD

**Issue by twojapiez** [sag-enhanced/sage-issues#47]
### Describe the feature

Mass edit account details. (Nicks,Profile pictures etc.)

### Use case

Easier managing accounts logging into every single accounts you have every time is slow.

### Additional context

Could use same settings ones for creating the accounts with custom details.

**Comment by Le0Developer** [comment]
> logging into every single accounts you have every time is slow

SAGE would need to do the same thing and hit Steam login ratelimits.
