### ISSUE TITLE
[Whitelist] Verification Email to Forwarding from Hostinger (BR)

### ISSUE THREAD

**Issue by TheRhanderson** [sag-enhanced/sage-issues#56]
### Describe the feature

I would like to request the whitelist of the message body that Hostinger (Brazil) sends to confirm the forwarding email.

### Use case

I'm using Hostinger's service in Brazil as my custom domain and I need to check message forwarding in Sage. It currently says that the email received by Hostinger is not valid, which is not the case.

### Additional context

Original email message is localized in pt-BR.
Screenshot: https://i.postimg.cc/dtWcRc2H/image.png

Part of the text:

Title: Verifique sua solicitação de encaminhamento de e-mail
Message:

Confirme sua solicitação de encaminhamento de e-mail
Para começar a encaminhar e-mails, você precisa verificar sua solicitação. Clique no botão abaixo para concluir o processo e começar a encaminhar seus e-mails

**Comment by Le0Developer** [comment]
Can you please post the full HTML body of the email? I need a way to make sure it's an forwarding email to prevent people from just using our mail serversr to sign up to hostinger.

**Comment by TheRhanderson** [comment]
Sure, shared on pastebin: https://pastebin.com/bFqpKNgB

**Comment by Le0Developer** [comment]
Looks it'll be impossible to determine it based on the content alone.
Can you send the email headers, maybe they have some kind of identifier in there?

**Comment by TheRhanderson** [comment]
This is the full header: https://pastebin.com/raw/xfCRVX3H

The only line I could guess is the first one with this 'bounces' text, as it contains the email where I want to receive the forwarding, its not the email from Hostinger that I own.

**Comment by Le0Developer** [comment]
There doesn't seem to be anything this is whitelistable by.
The return-path simply contains the receiving address, so if you were to setup a hostinger account, it'd be the same.

Unfortunately, I can't whitelist this. Please use a [documented Email Forwarding solution](https://sage.party/domains/email-forwarding/) instead.
