### ISSUE TITLE
Tags not saving when applying them to an account the first time

### ISSUE THREAD

**Issue by drowniscool** [sag-enhanced/sage-issues#6]
### Prerequisites

- [X] I asked in the [Discord server](https://sage.party/discord) and have been directed here.

### Describe the bug

When adding a tag to an account, I have to save it twice in order for the tag to actually save.

### To Reproduce

Add tag to a new account, click off the menu, and see that the tag has not saved to the account.

### Expected behavior

Tag should save to the account on the first try.

### Screenshots

![sage-windows-amd64_BeE6LCs4zn](https://github.com/sag-enhanced/sage-issues/assets/68257940/dc0c065d-b581-4124-a600-8bf1e4e10c08)

### Your Environment

Windows 10, AMD64

**Comment by Le0Developer** [comment]
Sadly can't reproduce.
