### ISSUE TITLE
Country displayed on Steam profile customization

### ISSUE THREAD

**Issue by BaldCult** [sag-enhanced/sage-issues#9]
### Describe the feature

Have an option for the country to be displayed on the profile as a random country (kind of like the random option for profile themes) and another option for the country to be set as the one from the ip's originating country.

### Use case

Just more customizability and randomness between the accounts being generated.

**Comment by Le0Developer** [comment]
Custom script support for location is coming soon.
Simply return a valid country **code** (like US) (see https://steamcommunity.com//actions/QueryLocations/ for a list)

You can also return an object with `{ country: "XX", state: "YY", city: "ZZZ" }`
